version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd,12345
      MYSQL_DATABASE: temperature_db
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: heslo
    volumes:
      - my-sql-db-vol:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
  go-api:
    build:
      context: .
      args:
        - GO_ENV=production
    volumes:
      - .:/app
    ports:
      - "80:8080"
    depends_on:
      - db

# Names our volumes
volumes:
  my-sql-db-vol:
